{% set name = "cocotb" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cocotb-{{ version }}.tar.gz
  sha256: 6e6495997ddb737dbcd47aa00b29d11f2237df8521e9b52064e8f59641231b4a
  patches:
    - patches/0001-remove-static-stdc.patch

build:
  number: 2
  skip: true  # [win]
  entry_points:
    - cocotb-config = cocotb.config:main
  run_exports:
    - {{ pin_subpackage("cocotb", max_pin="x") }}
  script:
    - {{ PYTHON }} -m pip install --no-deps . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - find-libpython
  run_constrained:
    - iverilog >=10.3
    - verilator >=5.004

test:
  imports:
    - cocotb
    - pygpi
  commands:
    - pip check
    - cocotb-config --help
  requires:
    - pip

about:
  home: https://www.cocotb.org
  dev_url: https://github.com/cocotb/cocotb
  summary: cocotb is a coroutine based cosimulation library for writing VHDL and Verilog testbenches in Python.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - cocotb/_vendor/tcl/license.terms
    - LICENSE.fli.acc
    - LICENSE.fli.mti
    - LICENSE.vhpi
    - LICENSE.vpi

extra:
  recipe-maintainers:
    - tianrui-wei
    - timkpaine
